[package]
name = "rt-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11.8"
glam = "0.30.1"
log = "0.4.27"
pollster = "0.4.0"
tobj = "4.0.3"
wgpu = { git = "https://github.com/gfx-rs/wgpu.git" }
winit = { version = "0.29", features = ["rwh_05"] }
wgsl_preprocessor = { path = "./wgsl_preprocessor" }
image = "0.25.6"
ash = "0.38.0"

[build-dependencies]
wgsl_preprocessor = { path = "./wgsl_preprocessor" }
